### PR TITLE
Add support for flatpak

### PR DESCRIPTION
**Pull request by hirefrank**
Snap is great but doesn't have everything. Add support for flatpak packages.

### CODE REVIEW

**Comment by iljo-dp** [comment]
To quote DHH directly when he was asked about flatpak earlier
"No, not interested in flatpak as a general replacement for apt. It's a different philosophy. I prefer apt."

**Comment by hirefrank** [comment]
FWIW, I prefer apt to and I don't think of Flatpak as a replacement anymore than I think of Snap as a replacement. That said not everything is available in apt.

Same is true for AppImages. Unfortunately the ecosystem is fragmented as much as we wish it not to be.

**Comment by dhh** [comment]
I think having flatpak available as an option is actually fine. I just didn't want to convert all our existing installers, or any future installers that can use apt, over to flatpak.

**Comment by dhh** [comment]
Hmm, it's not great that this halts the installation:

image

Is there a way to sidestep that @hirefrank? Otherwise we might just have to make it an optional for now.

**Pull request merged**
