### PR TITLE
Added the nord theme & kanagawa to omakub

### PR DESCRIPTION
**Pull request by iljo-dp**
Haven't tested if the gnome setting works, and obviously i'd need DHH to sign off on the background and the theming. It is all nord be he still needs to like it. 
#3 
Paper is from
https://github.com/linuxdotexe/nordic-wallpapers/blob/master/wallpapers/nord_lake.png
This also looked good imo
https://github.com/linuxdotexe/nordic-wallpapers/blob/master/wallpapers/ubuntu-frost.png

### CODE REVIEW

**Comment by iljo-dp** [comment]
if possible i'd like for someone to check all the themes in the respective apps :D

**Comment by iljo-dp** [comment]
Also added the kanagawa theme(trying atleast)
nvim, allacritty and zellij work, but not so sure about gnome, since the theme isn't normally installed, and I can't test gnome at this point in time

refer to 
https://github.com/Fausto-Korpsvart/Kanagawa-GKT-Theme 
is what I'd do, I can't figure it out and test it at this moment in time, sorry

**Comment by iljo-dp** [comment]
I realise the way i do kanagawa isn't the best solution(for gnome), could you give some input on this pull @dhh

**Comment by dhh** [comment]
We don't need any more theming than already done just with colors. So can drop that part of it.

**Comment by iljo-dp** [comment]
now kanagawa should be ready also

**Comment by dhh** [comment]
Thanks a bunch for your help on these! I picked some different backgrounds and tweaked a few settings, but your theme files were great.

**Pull request closed without merging**
