### PR TITLE
Create a optional install for 1password-cli, required to access secrets via SSH

### PR DESCRIPTION
**Pull request by eddygarcas**

### CODE REVIEW

**Comment by dhh** [comment]
Let's just combine this with the 1password installer and install both at the same time.

**Comment by eddygarcas** [comment]
Done, I've just merged both installation scripts into one.

**Comment by dhh** [comment]
If we are setting up the app repo for the cli, is it not possible to use that to install the gui too?

**Comment by eddygarcas** [comment]
> If we are setting up the app repo for the cli, is it not possible to use that to install the gui too?

I'll check this out, I think we can, just didn't want to mess up with the previous configuration. I'll update the PR shortly.

**Comment by dhh** [comment]
image

It's not working as-is.

**Pull request merged**
