### PR TITLE
Update: alacritty default font size from 7 to 10

### PR DESCRIPTION
**Pull request by 0ussamaBernou**
font size of 7 is too small for a default value, 10 is more reasonable

### CODE REVIEW

**Comment by iljo-dp** [comment]
this is dhh's personal opinionated script, and if 7 works for him that is kinda what matters in the end, this HIS script not yours, and imo changing font size is a personal change that is his call and not that of you, me or anyone else here tbf.

**Comment by j-collier** [comment]
If you try it on a framework 13 laptop it's pretty appropriately sized.

**Comment by gregmolnar** [comment]
Omakub is an opinionated setup script and you can adjust this after the installation if you are not happy with the default value. 
@0ussamaBernou would you mind closing the issue?

**Comment by dhh** [comment]
7 is set to look the best on the current Framework 13 screen. But I agree that it's too small for other screens. I'd very much like to come up with a scheme where we hit the right default size by checking PPI or something like that.

We COULD also just set default to 9 (my preference on most screens), but then overwrite it to 7 for that Framework screen.

**Comment by dhh** [comment]
Solved via https://github.com/basecamp/omakub/commit/59eb8fd299062b2361e1d711415f9c9b7824d1b0

**Comment by 0ussamaBernou** [comment]
> 7 is set to look the best on the current Framework 13 screen. But I agree that it's too small for other screens. I'd very much like to come up with a scheme where we hit the right default size by checking PPI or something like that.
> 
> We COULD also just set default to 9 (my preference on most screens), but then overwrite it to 7 for that Framework screen.

Yeah I agree, setting font size depending on the PPI would be the optimal solution here.

I'll try to work on it sometime

Also, the solution you ended up with is a good middle ground.

**Comment by 0ussamaBernou** [comment]
> 7 is set to look the best on the current Framework 13 screen. But I agree that it's too small for other screens. I'd very much like to come up with a scheme where we hit the right default size by checking PPI or something like that.
> 
> We COULD also just set default to 9 (my preference on most screens), but then overwrite it to 7 for that Framework screen.

Yeah I agree, setting font size depending on the PPI would be the optimal solution here.

I'll try to work on it sometime

Also, the solution you ended up with is a good middle ground.

**Pull request closed without merging**
